---
- name: k3s
  hosts: bot
  become_method: sudo
  become: yes
  become_user: root

  pre_tasks:

  - name: install 
    ansible.builtin.package: 
      name: 
        - curl
        - python3-pip 
        - apt-transport-https
        - python3-kubernetes
        - python3-jsonpatch

  - name: Install python package
    pip:
      name: 
        - pyyaml

  tasks:

  - name: create directory if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: foilv
      mode: 0775
    loop:
      - /home/foilv/.kube
      - /src/k3s

  - name: Download k3s.io
    become: yes
    get_url:
      url: "https://get.k3s.io"
      dest: "/src/k3s/k3s.sh"

  - name: sh k3s.sh
    become: yes
    ansible.builtin.shell:
      cmd: sh k3s.sh
      chdir: "/src/k3s"

  - name: start k3s
    become: yes
    service:
      name: k3s
      state: started
      enabled: yes

  - name: Add helm repo key 
    ansible.builtin.apt_key:
      url: https://baltocdn.com/helm/signing.asc
      state: present

  - name: add repo helm
    ansible.builtin.apt_repository:
      repo: deb https://baltocdn.com/helm/stable/debian/ all main
      state: present

  - name: install helm package
    ansible.builtin.package: 
      name: helm

  - name: Add helm repo
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: https://charts.bitnami.com/bitnami

  - name: Copying file /etc/rancher/k3s/k3s.yaml to /home/vika/.kube/config 
    ansible.builtin.fetch:
      src:  "/etc/rancher/k3s/k3s.yaml"
      dest: "/home/vika/.kube/config"
      flat: yes

  - name: Copying file /etc/rancher/k3s/k3s.yaml to /home/foilv/.kube/config
    ansible.builtin.copy:
      src:  "/etc/rancher/k3s/k3s.yaml"
      dest: "/home/foilv/.kube/config"
      owner: foilv
      group: foilv
      mode: '0600'
      remote_src: yes

  - name: change permissions for /home/foilv/.kube/config
    ansible.builtin.file:
      path: "/home/foilv/.kube/config"
      state: file
      owner: foilv
      group: foilv
      mode: "0600"
      
  roles:
    - geerlingguy.docker

